# This will run on Travis' 'new' container-based infrastructure
sudo: false
os: linux
dist: precise

language: c

# Blacklist
branches:
  except:
    - gh-pages

# Environment variables
env:
  global:
    - GH_REPO_NAME: OpENer
    - DOXYFILE: opener.doxyfile
    - GH_REPO_REF: github.com/EIPStackGroup/OpENer.git
    - secure: "RAyvtCis1g7WET5y0NsOsXt7eVLG0iNYoNNyJ+2XXy9BdcOFDsucWJAABAWyb2bf/lqeJ/tvmPRjAzPoQhId4zMxkLMKKEU6xXQqIoTSMsLOlb2R5WUVahnR/dHfoq3u3wXdmZZq/vRnDp9UXDDjyYDvSqIprpN0uvu666QLEGU="

# Install dependencies
addons:
  apt:
    packages:
      - doxygen
      - doxygen-doc
      - doxygen-latex
      - doxygen-gui
      - graphviz

#Prepare CppUTest from source, as package is not available
before_script:
  - cd $TRAVIS_BUILD_DIR/source
  - chmod +x $TRAVIS_BUILD_DIR/travis_scripts/installCppUTestDependency.sh
  - $TRAVIS_BUILD_DIR/travis_scripts/installCppUTestDependency.sh

# Build your code e.g. by calling make
script:
  - cd $TRAVIS_BUILD_DIR/bin/posix
  - cmake -DOpENer_PLATFORM:STRING="POSIX" -DCMAKE_BUILD_TYPE:STRING="" -DOpENer_64_BIT_DATA_TYPES_ENABLED:BOOL=ON -DOpENer_TESTS:BOOL=ON -DCPPUTEST_HOME:PATH=$TRAVIS_BUILD_DIR/source/dependencies/cpputest -DCPPUTEST_LIBRARY:FILEPATH=$TRAVIS_BUILD_DIR/source/dependencies/cpputest/src/CppUTest/libCppUTest.a -DCPPUTESTEXT_LIBRARY:FILEPATH=$TRAVIS_BUILD_DIR/source/dependencies/cpputest/src/CppUTestExt/libCppUTestExt.a ../../source
  - make
  - make test

# Generate and deploy documentation
after_success:
  - cd $TRAVIS_BUILD_DIR/source
  - chmod +x $TRAVIS_BUILD_DIR/travis_scripts/generateDocumentationAndDeploy.sh
  - $TRAVIS_BUILD_DIR/travis_scripts/generateDocumentationAndDeploy.sh
